services:
  redis:
    image: redis:7.4.1-alpine
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: smartshield
      POSTGRES_USER: insat
      POSTGRES_PASSWORD: insat
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insat -d smartshield"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - db
    ports:
      - "3000:3000"
    restart: always
    networks:
      rabbitmq_net:

volumes:
  redis-data:
  pgadmin-data:
  db-data:

networks:
  rabbitmq_net:
    name: rabbitmq_net
    driver: bridge
    external: true