services:
  redis:
    image: redis:7.4.1-alpine
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: ./backend
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: mytoken
      INFLUXDB_ORG: myorg
      INFLUXDB_BUCKET: mybucket
    depends_on:
      - redis
      - influxdb
    ports:
      - "8000:8000"

  celery_worker:
    build:
      context: ./backend
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: mytoken
      INFLUXDB_ORG: myorg
      INFLUXDB_BUCKET: mybucket
    depends_on:
      - redis
      - influxdb
    command: celery -A app.tasks worker --loglevel=info

  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: mybucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mytoken

volumes:
  redis-data:
  influxdb-data: