# Stage 1: Build
FROM node:23.1-alpine AS builder
RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml nx.json ./
COPY apps/backend ./apps/backend

RUN pnpm install --frozen-lockfile
RUN pnpm build backend

# Stage 2: Production
FROM node:23.1-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/backend ./
COPY --from=builder /app/package.json ./
COPY --from=builder /app/pnpm-lock.yaml ./

RUN pnpm install --prod --frozen-lockfile

EXPOSE 3000

CMD ["node", "main.js"]
